-- =====================================================================
--  Health Setu — demo database schema (PostgreSQL 14+)
--  Multi-facility healthcare network + patient-controlled records layer.
--  All data loaded into this schema is 100% SYNTHETIC.
--  WARNING: running this file wipes and recreates the public schema.
-- =====================================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
CREATE EXTENSION IF NOT EXISTS btree_gist;   -- needed for "no double-booked bed" constraints

-- ---------------------------------------------------------------------
--  1. Network: facilities, departments, people
-- ---------------------------------------------------------------------
CREATE TABLE facilities (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(10)  NOT NULL UNIQUE,
    name               VARCHAR(120) NOT NULL UNIQUE,
    facility_type      VARCHAR(30)  NOT NULL CHECK (facility_type IN ('multispeciality_hospital','general_hospital','government_hospital','nursing_home','diagnostic_centre')),
    ownership          VARCHAR(12)  NOT NULL CHECK (ownership IN ('private','government','trust')),
    locality           VARCHAR(120),
    city               VARCHAR(80)  NOT NULL,
    state              VARCHAR(80)  NOT NULL DEFAULT 'West Bengal',
    pincode            VARCHAR(6),
    latitude           NUMERIC(9,6) NOT NULL,
    longitude          NUMERIC(9,6) NOT NULL,
    phone              VARCHAR(20),
    emergency_24x7     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_participating   BOOLEAN      NOT NULL DEFAULT TRUE,   -- shares availability with the network
    joined_network_at  TIMESTAMP    NOT NULL,
    is_synthetic       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE facility_services (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id   INT          NOT NULL REFERENCES facilities(id),
    service       VARCHAR(40)  NOT NULL,
    is_available  BOOLEAN      NOT NULL DEFAULT TRUE,
    note          TEXT,
    updated_at    TIMESTAMP    NOT NULL,
    UNIQUE (facility_id, service)
);

CREATE TABLE departments (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(10)  NOT NULL UNIQUE,
    name             VARCHAR(100) NOT NULL UNIQUE,
    floor            SMALLINT     NOT NULL,
    phone_extension  VARCHAR(10)
);

CREATE TABLE doctors (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code     VARCHAR(20)  NOT NULL UNIQUE,
    facility_id       INT          NOT NULL REFERENCES facilities(id),
    first_name        VARCHAR(60)  NOT NULL,
    last_name         VARCHAR(60)  NOT NULL,
    gender            CHAR(1)      NOT NULL CHECK (gender IN ('M','F','O')),
    department_id     INT          NOT NULL REFERENCES departments(id),
    specialization    VARCHAR(100) NOT NULL,
    qualification     VARCHAR(100) NOT NULL,
    registration_no   VARCHAR(30)  NOT NULL UNIQUE,
    phone             VARCHAR(20)  NOT NULL,
    email             VARCHAR(120) NOT NULL UNIQUE,
    consultation_fee  NUMERIC(10,2) NOT NULL CHECK (consultation_fee >= 0),
    joined_on         DATE         NOT NULL,
    left_on           DATE,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE staff (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code   VARCHAR(20)  NOT NULL UNIQUE,
    facility_id     INT          NOT NULL REFERENCES facilities(id),
    first_name      VARCHAR(60)  NOT NULL,
    last_name       VARCHAR(60)  NOT NULL,
    gender          CHAR(1)      NOT NULL CHECK (gender IN ('M','F','O')),
    role            VARCHAR(30)  NOT NULL CHECK (role IN ('nurse','receptionist','lab_technician','pharmacist','billing','admin')),
    department_id   INT          REFERENCES departments(id),
    shift           VARCHAR(10)  NOT NULL CHECK (shift IN ('morning','evening','night','general')),
    phone           VARCHAR(20)  NOT NULL,
    email           VARCHAR(120) NOT NULL UNIQUE,
    joined_on       DATE         NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE patients (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_code                VARCHAR(20)  NOT NULL UNIQUE,
    first_name                  VARCHAR(60)  NOT NULL,
    last_name                   VARCHAR(60)  NOT NULL,
    gender                      CHAR(1)      NOT NULL CHECK (gender IN ('M','F','O')),
    date_of_birth               DATE         NOT NULL,
    blood_group                 VARCHAR(3)   CHECK (blood_group IN ('A+','A-','B+','B-','AB+','AB-','O+','O-')),
    phone                       VARCHAR(20),
    email                       VARCHAR(120),
    address                     TEXT,
    city                        VARCHAR(80),
    state                       VARCHAR(80),
    pincode                     VARCHAR(6),
    emergency_contact_name      VARCHAR(120),
    emergency_contact_relation  VARCHAR(30),
    emergency_contact_phone     VARCHAR(20),
    abha_address                VARCHAR(80)  UNIQUE,   -- FAKE, ends in @demo; shows where an ABHA link would live
    registered_at               TIMESTAMP    NOT NULL
);

CREATE TABLE patient_allergies (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      INT          NOT NULL REFERENCES patients(id),
    allergen        VARCHAR(80)  NOT NULL,
    allergen_class  VARCHAR(40)  NOT NULL,            -- matched against medications.drug_classes
    reaction        VARCHAR(120),
    severity        VARCHAR(10)  NOT NULL CHECK (severity IN ('mild','moderate','severe')),
    source          VARCHAR(20)  NOT NULL CHECK (source IN ('patient_reported','clinician_recorded')),
    recorded_at     TIMESTAMP    NOT NULL
);

CREATE TABLE insurance_providers (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(120) NOT NULL UNIQUE,
    provider_type  VARCHAR(10)  NOT NULL CHECK (provider_type IN ('private','public')),
    helpline       VARCHAR(20)
);

CREATE TABLE patient_insurance (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      INT           NOT NULL REFERENCES patients(id),
    provider_id     INT           NOT NULL REFERENCES insurance_providers(id),
    policy_number   VARCHAR(40)   NOT NULL UNIQUE,
    coverage_limit  NUMERIC(12,2) NOT NULL CHECK (coverage_limit > 0),
    valid_from      DATE          NOT NULL,
    valid_to        DATE          NOT NULL,
    CHECK (valid_to > valid_from)
);

-- ---------------------------------------------------------------------
--  2. Facility
-- ---------------------------------------------------------------------
CREATE TABLE wards (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id    INT           NOT NULL REFERENCES facilities(id),
    name           VARCHAR(80)   NOT NULL,
    ward_type      VARCHAR(20)   NOT NULL CHECK (ward_type IN ('general','pediatric','maternity','icu','emergency','private')),
    department_id  INT           REFERENCES departments(id),
    floor          SMALLINT      NOT NULL,
    daily_rate     NUMERIC(10,2) NOT NULL CHECK (daily_rate >= 0),
    UNIQUE (facility_id, name)
);

CREATE TABLE beds (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id         INT         NOT NULL REFERENCES wards(id),
    bed_number      VARCHAR(10) NOT NULL,
    is_operational  BOOLEAN     NOT NULL DEFAULT TRUE,
    UNIQUE (ward_id, bed_number)
);

-- ---------------------------------------------------------------------
--  3. Clinical
-- ---------------------------------------------------------------------
CREATE TABLE icd10_codes (
    code           VARCHAR(10) PRIMARY KEY,
    description    TEXT        NOT NULL,
    department_id  INT         REFERENCES departments(id),
    is_chronic     BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE TABLE appointments (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id   INT         NOT NULL REFERENCES facilities(id),
    patient_id    INT         NOT NULL REFERENCES patients(id),
    doctor_id     INT         NOT NULL REFERENCES doctors(id),
    scheduled_at  TIMESTAMP   NOT NULL,
    status        VARCHAR(12) NOT NULL CHECK (status IN ('scheduled','completed','cancelled','no_show')),
    visit_type    VARCHAR(12) NOT NULL CHECK (visit_type IN ('new','follow_up')),
    reason        TEXT,
    created_at    TIMESTAMP   NOT NULL,
    UNIQUE (doctor_id, scheduled_at),
    CHECK (created_at <= scheduled_at)
);

CREATE TABLE admissions (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_code         VARCHAR(20) NOT NULL UNIQUE,
    facility_id            INT         NOT NULL REFERENCES facilities(id),
    patient_id             INT         NOT NULL REFERENCES patients(id),
    attending_doctor_id    INT         NOT NULL REFERENCES doctors(id),
    bed_id                 INT         NOT NULL REFERENCES beds(id),
    admission_type         VARCHAR(12) NOT NULL CHECK (admission_type IN ('emergency','planned','transfer')),
    admitted_at            TIMESTAMP   NOT NULL,
    discharged_at          TIMESTAMP,
    status                 VARCHAR(12) NOT NULL CHECK (status IN ('admitted','discharged')),
    reason                 TEXT,
    discharge_disposition  VARCHAR(12) CHECK (discharge_disposition IN ('recovered','improved','referred','lama','deceased')),
    discharge_summary      TEXT,
    CHECK (discharged_at IS NULL OR discharged_at > admitted_at),
    CHECK ((status = 'admitted') = (discharged_at IS NULL)),
    -- the database itself refuses to put two patients in one bed at the same time
    EXCLUDE USING gist (bed_id WITH =,
        tsrange(admitted_at, COALESCE(discharged_at, 'infinity'::timestamp)) WITH &&),
    -- ...or one patient in two beds at the same time
    EXCLUDE USING gist (patient_id WITH =,
        tsrange(admitted_at, COALESCE(discharged_at, 'infinity'::timestamp)) WITH &&)
);

CREATE TABLE diagnoses (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      INT         NOT NULL REFERENCES patients(id),
    doctor_id       INT         NOT NULL REFERENCES doctors(id),
    icd_code        VARCHAR(10) NOT NULL REFERENCES icd10_codes(code),
    appointment_id  INT         REFERENCES appointments(id),
    admission_id    INT         REFERENCES admissions(id),
    diagnosed_at    TIMESTAMP   NOT NULL,
    diagnosis_type  VARCHAR(10) NOT NULL CHECK (diagnosis_type IN ('primary','secondary')),
    severity        VARCHAR(10) NOT NULL CHECK (severity IN ('mild','moderate','severe')),
    notes           TEXT,
    CHECK (appointment_id IS NOT NULL OR admission_id IS NOT NULL)
);

CREATE TABLE vitals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_id      INT          NOT NULL REFERENCES admissions(id),
    recorded_by       INT          REFERENCES staff(id),
    recorded_at       TIMESTAMP    NOT NULL,
    temperature_c     NUMERIC(4,1),
    pulse_bpm         SMALLINT,
    bp_systolic       SMALLINT,
    bp_diastolic      SMALLINT,
    respiratory_rate  SMALLINT,
    spo2_percent      SMALLINT CHECK (spo2_percent BETWEEN 0 AND 100)
);

-- ---------------------------------------------------------------------
--  4. Pharmacy
-- ---------------------------------------------------------------------
CREATE TABLE medications (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(120)  NOT NULL UNIQUE,
    generic_name           VARCHAR(120)  NOT NULL,
    form                   VARCHAR(20)   NOT NULL CHECK (form IN ('tablet','capsule','syrup','injection','inhaler','cream','sachet','iv_fluid')),
    strength               VARCHAR(40),
    drug_classes           TEXT[]        NOT NULL DEFAULT '{}',
    unit_price             NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    requires_prescription  BOOLEAN       NOT NULL DEFAULT TRUE
);

-- DEMO interaction rules — a small teaching set, not a clinical reference
CREATE TABLE drug_interactions (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_a_id INT          NOT NULL REFERENCES medications(id),
    medication_b_id INT          NOT NULL REFERENCES medications(id),
    severity        VARCHAR(16)  NOT NULL CHECK (severity IN ('minor','moderate','major','contraindicated')),
    description     TEXT         NOT NULL,
    recommendation  TEXT         NOT NULL,
    CHECK (medication_a_id < medication_b_id),
    UNIQUE (medication_a_id, medication_b_id)
);

CREATE TABLE drug_condition_cautions (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medication_id   INT          NOT NULL REFERENCES medications(id),
    icd_prefix      VARCHAR(10)  NOT NULL,           -- e.g. 'N18' matches N18.x
    severity        VARCHAR(16)  NOT NULL CHECK (severity IN ('minor','moderate','major','contraindicated')),
    description     TEXT         NOT NULL,
    recommendation  TEXT         NOT NULL,
    UNIQUE (medication_id, icd_prefix)
);

CREATE TABLE prescriptions (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id     INT       NOT NULL REFERENCES facilities(id),
    patient_id      INT       NOT NULL REFERENCES patients(id),
    doctor_id       INT       NOT NULL REFERENCES doctors(id),
    appointment_id  INT       REFERENCES appointments(id),
    admission_id    INT       REFERENCES admissions(id),
    prescribed_at   TIMESTAMP NOT NULL,
    notes           TEXT,
    CHECK (appointment_id IS NOT NULL OR admission_id IS NOT NULL)
);

CREATE TABLE prescription_items (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id  INT         NOT NULL REFERENCES prescriptions(id) ON DELETE CASCADE,
    medication_id    INT         NOT NULL REFERENCES medications(id),
    dosage           VARCHAR(40) NOT NULL,
    frequency        VARCHAR(40) NOT NULL,
    duration_days    SMALLINT    NOT NULL CHECK (duration_days > 0),
    quantity         INT         NOT NULL CHECK (quantity > 0),
    instructions     TEXT
);

CREATE TABLE pharmacy_inventory (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id       INT          NOT NULL REFERENCES facilities(id),
    medication_id     INT          NOT NULL REFERENCES medications(id),
    batch_number      VARCHAR(30)  NOT NULL UNIQUE,
    quantity_on_hand  INT          NOT NULL CHECK (quantity_on_hand >= 0),
    reorder_level     INT          NOT NULL,
    expiry_date       DATE         NOT NULL,
    supplier          VARCHAR(120),
    received_on       DATE         NOT NULL
);

-- ---------------------------------------------------------------------
--  5. Laboratory
-- ---------------------------------------------------------------------
CREATE TABLE lab_tests (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)   NOT NULL UNIQUE,
    name        VARCHAR(100)  NOT NULL,
    category    VARCHAR(40)   NOT NULL,
    unit        VARCHAR(20),
    normal_min  NUMERIC(10,3),
    normal_max  NUMERIC(10,3),
    price       NUMERIC(10,2) NOT NULL
);

CREATE TABLE lab_orders (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id     INT         NOT NULL REFERENCES facilities(id),
    patient_id      INT         NOT NULL REFERENCES patients(id),
    doctor_id       INT         NOT NULL REFERENCES doctors(id),
    appointment_id  INT         REFERENCES appointments(id),
    admission_id    INT         REFERENCES admissions(id),
    ordered_at      TIMESTAMP   NOT NULL,
    priority        VARCHAR(10) NOT NULL CHECK (priority IN ('routine','urgent')),
    status          VARCHAR(10) NOT NULL CHECK (status IN ('pending','completed','cancelled'))
);

CREATE TABLE lab_results (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_order_id   INT           NOT NULL REFERENCES lab_orders(id) ON DELETE CASCADE,
    lab_test_id    INT           NOT NULL REFERENCES lab_tests(id),
    result_value   NUMERIC(10,3) NOT NULL,
    flag           VARCHAR(6)    NOT NULL CHECK (flag IN ('normal','high','low')),
    resulted_at    TIMESTAMP     NOT NULL,
    technician_id  INT           REFERENCES staff(id),
    UNIQUE (lab_order_id, lab_test_id)
);

-- ---------------------------------------------------------------------
--  6. Billing & insurance
-- ---------------------------------------------------------------------
CREATE TABLE invoices (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number  VARCHAR(30)   NOT NULL UNIQUE,
    facility_id     INT           NOT NULL REFERENCES facilities(id),
    patient_id      INT           NOT NULL REFERENCES patients(id),
    appointment_id  INT           REFERENCES appointments(id),
    admission_id    INT           REFERENCES admissions(id),
    invoice_type    VARCHAR(3)    NOT NULL CHECK (invoice_type IN ('opd','ipd')),
    issued_at       TIMESTAMP     NOT NULL,
    subtotal        NUMERIC(12,2) NOT NULL,
    discount        NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax             NUMERIC(12,2) NOT NULL DEFAULT 0,   -- most healthcare services are GST-exempt in India
    total_amount    NUMERIC(12,2) NOT NULL,
    status          VARCHAR(20)   NOT NULL CHECK (status IN ('paid','partially_paid','unpaid','insurance_pending')),
    CHECK (total_amount = subtotal - discount + tax)
);

CREATE TABLE invoice_items (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   INT           NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    item_type    VARCHAR(20)   NOT NULL CHECK (item_type IN ('consultation','room','doctor_visit','nursing','lab','pharmacy','procedure','icu_charges')),
    description  TEXT          NOT NULL,
    quantity     NUMERIC(10,2) NOT NULL,
    unit_price   NUMERIC(12,2) NOT NULL,
    amount       NUMERIC(12,2) NOT NULL
);

CREATE TABLE payments (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id        INT           NOT NULL REFERENCES invoices(id),
    paid_at           TIMESTAMP     NOT NULL,
    amount            NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    method            VARCHAR(12)   NOT NULL CHECK (method IN ('cash','upi','card','netbanking','insurance')),
    reference_number  VARCHAR(40)
);

CREATE TABLE insurance_claims (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number          VARCHAR(30)   NOT NULL UNIQUE,
    invoice_id            INT           NOT NULL UNIQUE REFERENCES invoices(id),
    patient_insurance_id  INT           NOT NULL REFERENCES patient_insurance(id),
    claimed_amount        NUMERIC(12,2) NOT NULL,
    approved_amount       NUMERIC(12,2),
    status                VARCHAR(20)   NOT NULL CHECK (status IN ('submitted','under_review','approved','partially_approved','rejected')),
    submitted_at          TIMESTAMP     NOT NULL,
    settled_at            TIMESTAMP,
    rejection_reason      TEXT
);

-- ---------------------------------------------------------------------
--  7. Access control & audit
-- ---------------------------------------------------------------------
CREATE TABLE roles (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(30) NOT NULL UNIQUE,
    description  TEXT
);

CREATE TABLE users (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       VARCHAR(60)  NOT NULL UNIQUE,
    password_hash  VARCHAR(200) NOT NULL,
    role_id        INT          NOT NULL REFERENCES roles(id),
    doctor_id      INT          UNIQUE REFERENCES doctors(id),
    staff_id       INT          UNIQUE REFERENCES staff(id),
    patient_id     INT          UNIQUE REFERENCES patients(id),
    facility_id    INT          REFERENCES facilities(id),      -- scope for doctors & staff
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP    NOT NULL,
    last_login_at  TIMESTAMP,
    CHECK (num_nonnulls(doctor_id, staff_id, patient_id) <= 1)
);

-- ---------------------------------------------------------------------
--  8. Health Setu layer: documents, AI extraction, timeline, consent, availability
-- ---------------------------------------------------------------------
-- Original files are immutable (see trigger below). storage_uri points into the file store.
CREATE TABLE documents (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code        VARCHAR(20)  NOT NULL UNIQUE,
    patient_id           INT          NOT NULL REFERENCES patients(id),
    document_type        VARCHAR(20)  NOT NULL CHECK (document_type IN ('prescription','lab_report','discharge_summary','imaging_report','other')),
    source               VARCHAR(20)  NOT NULL CHECK (source IN ('patient_upload','facility_upload')),
    issuing_facility_id  INT          REFERENCES facilities(id),   -- NULL when issued outside the network
    issuer_name          VARCHAR(160) NOT NULL,                    -- as printed on the document
    document_date        DATE,
    storage_uri          TEXT         NOT NULL,
    original_filename    VARCHAR(200),
    mime_type            VARCHAR(60)  NOT NULL,
    file_size_bytes      INT,
    sha256               CHAR(64)     NOT NULL,
    uploaded_by_user_id  INT          REFERENCES users(id),
    uploaded_at          TIMESTAMP    NOT NULL,
    is_synthetic         BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Every OCR/AI pass is a new version; the patient reviews the latest one.
CREATE TABLE document_extractions (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id            INT          NOT NULL REFERENCES documents(id),
    version                SMALLINT     NOT NULL DEFAULT 1,
    extractor              VARCHAR(60)  NOT NULL,
    extracted_data         JSONB        NOT NULL,
    confidence             NUMERIC(4,3) CHECK (confidence BETWEEN 0 AND 1),
    low_confidence_fields  TEXT[]       NOT NULL DEFAULT '{}',
    status                 VARCHAR(16)  NOT NULL CHECK (status IN ('pending_review','verified','corrected','rejected')),
    reviewed_by_user_id    INT          REFERENCES users(id),
    reviewed_at            TIMESTAMP,
    review_note            TEXT,
    created_at             TIMESTAMP    NOT NULL,
    UNIQUE (document_id, version),
    CHECK ((status = 'pending_review') = (reviewed_at IS NULL))
);

-- Append-only, source-linked patient history. Corrections are new rows that point at what they supersede.
CREATE TABLE timeline_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id           INT          NOT NULL REFERENCES patients(id),
    event_type           VARCHAR(16)  NOT NULL CHECK (event_type IN ('opd_visit','admission','discharge','diagnosis','prescription','lab_result','document')),
    category             VARCHAR(16)  NOT NULL CHECK (category IN ('encounters','diagnoses','prescriptions','lab_results','documents')),
    occurred_at          TIMESTAMP    NOT NULL,
    title                TEXT         NOT NULL,
    summary              TEXT,
    facility_id          INT          REFERENCES facilities(id),
    source_name          VARCHAR(160) NOT NULL,       -- facility or outside issuer, shown to the user
    origin               VARCHAR(16)  NOT NULL CHECK (origin IN ('facility_record','patient_upload')),
    source_table         VARCHAR(40)  NOT NULL,
    source_id            BIGINT       NOT NULL,
    document_id          INT          REFERENCES documents(id),
    supersedes_event_id  BIGINT       REFERENCES timeline_events(id),
    created_at           TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE consent_requests (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       INT          NOT NULL REFERENCES patients(id),
    doctor_id        INT          NOT NULL REFERENCES doctors(id),
    facility_id      INT          NOT NULL REFERENCES facilities(id),
    purpose          VARCHAR(16)  NOT NULL CHECK (purpose IN ('consultation','follow_up','second_opinion','referral','emergency')),
    requested_scope  TEXT[]       NOT NULL CHECK (requested_scope <@ ARRAY['encounters','diagnoses','prescriptions','lab_results','documents']::text[] AND cardinality(requested_scope) > 0),
    requested_hours  INT          NOT NULL CHECK (requested_hours BETWEEN 1 AND 8760),
    message          TEXT,
    status           VARCHAR(10)  NOT NULL CHECK (status IN ('pending','approved','denied','cancelled','expired')),
    requested_at     TIMESTAMP    NOT NULL,
    responded_at     TIMESTAMP,
    CHECK ((status = 'pending') = (responded_at IS NULL) OR status = 'expired')
);

CREATE TABLE consent_grants (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          INT          UNIQUE REFERENCES consent_requests(id),
    patient_id          INT          NOT NULL REFERENCES patients(id),
    doctor_id           INT          NOT NULL REFERENCES doctors(id),
    grant_type          VARCHAR(20)  NOT NULL CHECK (grant_type IN ('patient_granted','emergency_override')),
    scope               TEXT[]       NOT NULL CHECK (scope <@ ARRAY['encounters','diagnoses','prescriptions','lab_results','documents']::text[] AND cardinality(scope) > 0),
    granted_at          TIMESTAMP    NOT NULL,
    expires_at          TIMESTAMP    NOT NULL,
    revoked_at          TIMESTAMP,
    revoked_by_user_id  INT          REFERENCES users(id),
    revoke_reason       TEXT,
    justification       TEXT,        -- required for emergency overrides
    CHECK (expires_at > granted_at),
    CHECK (revoked_at IS NULL OR revoked_at >= granted_at),
    CHECK (grant_type <> 'emergency_override' OR justification IS NOT NULL),
    CHECK (grant_type <> 'patient_granted' OR request_id IS NOT NULL)
);

-- Hospitals REPORT availability; it is indicative until confirmed.
CREATE TABLE bed_availability_reports (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facility_id          INT          NOT NULL REFERENCES facilities(id),
    ward_type            VARCHAR(20)  NOT NULL CHECK (ward_type IN ('general','pediatric','maternity','icu','emergency','private')),
    total_beds           INT          NOT NULL CHECK (total_beds >= 0),
    available_beds       INT          NOT NULL CHECK (available_beds >= 0),
    reported_at          TIMESTAMP    NOT NULL,
    reported_by_user_id  INT          REFERENCES users(id),
    source               VARCHAR(20)  NOT NULL CHECK (source IN ('hospital_confirmed','auto_computed')),
    note                 TEXT,
    CHECK (available_beds <= total_beds)
);

CREATE TABLE ai_summaries (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id           INT          NOT NULL REFERENCES patients(id),
    doctor_id            INT          NOT NULL REFERENCES doctors(id),
    consent_grant_id     INT          REFERENCES consent_grants(id),
    generated_at         TIMESTAMP    NOT NULL,
    model                VARCHAR(80)  NOT NULL,
    summary_text         TEXT         NOT NULL,
    citations            JSONB        NOT NULL DEFAULT '[]',   -- [{"sentence": 1, "timeline_event_id": 123}, ...]
    included_unverified  BOOLEAN      NOT NULL DEFAULT FALSE,
    disclaimer           TEXT         NOT NULL DEFAULT 'AI-generated summary to assist a clinician. Verify against source records. Not a diagnosis.'
);

-- ---------------------------------------------------------------------
--  9. Audit log (every access, every consent decision)
-- ---------------------------------------------------------------------
CREATE TABLE audit_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INT         REFERENCES users(id),
    username_attempted  VARCHAR(60),
    action              VARCHAR(20) NOT NULL CHECK (action IN ('LOGIN','LOGIN_FAILED','LOGOUT','VIEW','CREATE','UPDATE','DELETE','EXPORT',
                                                            'UPLOAD','VERIFY','CONSENT_REQUEST','CONSENT_GRANT','CONSENT_DENY',
                                                            'CONSENT_REVOKE','CONSENT_EXPIRE','EMERGENCY_ACCESS','AI_SUMMARY')),
    table_name          VARCHAR(40),
    record_id           BIGINT,
    patient_id          INT         REFERENCES patients(id),       -- whose data was touched
    consent_grant_id    INT         REFERENCES consent_grants(id), -- legal basis for cross-facility access
    ip_address          INET,
    occurred_at         TIMESTAMP   NOT NULL,
    details             TEXT
);

-- ---------------------------------------------------------------------
--  Append-only guard: original documents and timeline history can never be edited or deleted
-- ---------------------------------------------------------------------
CREATE FUNCTION forbid_modification() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION '% is append-only: add a new row (e.g. supersedes_event_id) instead of %', TG_TABLE_NAME, TG_OP;
END $$;
CREATE TRIGGER documents_append_only       BEFORE UPDATE OR DELETE ON documents       FOR EACH ROW EXECUTE FUNCTION forbid_modification();
CREATE TRIGGER timeline_events_append_only BEFORE UPDATE OR DELETE ON timeline_events FOR EACH ROW EXECUTE FUNCTION forbid_modification();

-- ---------------------------------------------------------------------
--  Indexes (foreign keys and common filters)
-- ---------------------------------------------------------------------
CREATE UNIQUE INDEX one_active_admission_per_patient ON admissions(patient_id) WHERE discharged_at IS NULL;
CREATE INDEX idx_appointments_patient   ON appointments(patient_id);
CREATE INDEX idx_appointments_time      ON appointments(scheduled_at);
CREATE INDEX idx_admissions_patient     ON admissions(patient_id);
CREATE INDEX idx_admissions_status      ON admissions(status);
CREATE INDEX idx_diagnoses_patient      ON diagnoses(patient_id);
CREATE INDEX idx_diagnoses_code         ON diagnoses(icd_code);
CREATE INDEX idx_vitals_admission       ON vitals(admission_id, recorded_at);
CREATE INDEX idx_prescriptions_patient  ON prescriptions(patient_id);
CREATE INDEX idx_rx_items_prescription  ON prescription_items(prescription_id);
CREATE INDEX idx_lab_orders_patient     ON lab_orders(patient_id);
CREATE INDEX idx_lab_results_order      ON lab_results(lab_order_id);
CREATE INDEX idx_lab_results_flag       ON lab_results(flag) WHERE flag <> 'normal';
CREATE INDEX idx_invoices_patient       ON invoices(patient_id);
CREATE INDEX idx_invoice_items_invoice  ON invoice_items(invoice_id);
CREATE INDEX idx_payments_invoice       ON payments(invoice_id);
CREATE INDEX idx_audit_user_time        ON audit_log(user_id, occurred_at);
CREATE INDEX idx_audit_time             ON audit_log(occurred_at);
CREATE INDEX idx_audit_patient          ON audit_log(patient_id, occurred_at);
CREATE INDEX idx_doctors_facility       ON doctors(facility_id);
CREATE INDEX idx_admissions_facility    ON admissions(facility_id, status);
CREATE INDEX idx_prescriptions_facility ON prescriptions(facility_id);
CREATE INDEX idx_documents_patient      ON documents(patient_id);
CREATE INDEX idx_extractions_document   ON document_extractions(document_id, version DESC);
CREATE INDEX idx_timeline_patient       ON timeline_events(patient_id, occurred_at);
CREATE INDEX idx_timeline_source        ON timeline_events(source_table, source_id);
CREATE INDEX idx_consent_req_patient    ON consent_requests(patient_id, status);
CREATE INDEX idx_consent_grants_lookup  ON consent_grants(doctor_id, patient_id, expires_at);
CREATE INDEX idx_bed_reports_latest     ON bed_availability_reports(facility_id, ward_type, reported_at DESC);
CREATE INDEX idx_allergies_patient      ON patient_allergies(patient_id);

